travis:
  secure:
    BINSTAR_TOKEN: iezEF3dHI3vPQPpUfRl9j3SDVcEYaoKIBr+/vOZFm7JnePhNcLo5llr5FqmMHOG4kmp/WwBDfINYv7TpKD6fa8JEC+YyuAeE7cIEJvqWrpHCqJ1N+73MJwwoGeTqP2jqYSDIIFZio3biCpB47oN9djmQyKFv3aoZR2OUYMRiIw1+Jb3IX/TLW3AyCEQvLdNsBiGMulT68/wH8T5tWdPaG4SKJm5fcds/0Ccjp9Mf+ySZRUlJdeqUNlEi1e5evpmfjXjOqJ2UGXKco0SIkW+av+TmGCx+uhF5tsZWyFvl8B6jOZ+m6+FeG8bLEaCwUy4mGeRhzUmzdvOZlrpD85xkSaIRIrzKcODyJokS+kCVOwK+96HF7ZpzLWY8BC+yztt0j79H5dE2UhzZTQ8W3VA0kNYK7crpLU1iu8o+QjzBe1GyhdFNWXGjmTLGh3M2c9Yv4GCadLjE29jQ2hZaH05EsfGjWl/py12jA7mp3oSPEEctx7gUlsgJHxOPasBbGALBhCVwUB3zHfxAs2bXdvtTzpXVpy3+Bw10Q8TjmjSBo4/Xu4b8NjmqQApe7Z4v4A8dbfWQmTXd+zIzzB1crtI+7DgzLPiMFwp8Bha3NLm/URW2eK4URYbxul1lbc6zPrz/TpnhAtOlXWcl0yhUR8LW4wplHLhAoNJl3LIwW8kINfw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
